### ISSUE TITLE
De referentiedata mist data van de tabbladen nationaliteit en opleidingen

### ISSUE THREAD

**Issue by cwiesenekker** [vereniging-corponet/vera-referentiedata#7]
Enkel in de Excel zijn die terug te vinden. De CSV mist deze data.

**Comment by EwoutvdWielen** [comment]
Deze referentiedata wordt niet beheerd door VERA en daarom niet opgenomen in de lijst. Je kunt hiervoor de standaarden opvragen bij:
- Nationaliteitcoderingen: https://nl.wikipedia.org/wiki/ISO_3166-1
- BRIN-coderingen: https://instellingsinformatie.duo.nl/public/websitecfi/
